#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop power4d.service || true
            systemctl disable power4d.service || true
        fi
        ;;
esac

exit 0
